
app:
  url: http://localhost:8090
server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/StudentPortal
    username: postgres
    password: 5151
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: POSTGRESQL
    show-sql: true

  security:
    user:
      name: spring
      password: tatar